steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/devops-pipeline-arun-01-waa/my-repo/website', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/devops-pipeline-arun-01-waa/my-repo/website']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'my-website', '--image', 'asia-south1-docker.pkg.dev/devops-pipeline-arun-01-waa/my-repo/website', '--region', 'asia-south1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'asia-south1-docker.pkg.dev/devops-pipeline-arun-01-waa/my-repo/website'
