steps:
# Step 1: Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/devops-pipeline-arun-01-waa/my-repo/website', '.']

# Step 2: Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/devops-pipeline-arun-01-waa/my-repo/website']

# Step 3: Deploy (With the PORT FIX)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'my-website'
  - '--image'
  - 'asia-south1-docker.pkg.dev/devops-pipeline-arun-01-waa/my-repo/website'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'   # <--- ADDED THIS
  - '80'       # <--- ADDED THIS

images:
- 'asia-south1-docker.pkg.dev/devops-pipeline-arun-01-waa/my-repo/website'

options:
  logging: CLOUD_LOGGING_ONLY
